### ISSUE TITLE
VMB7IN module sensors “unavailable” 

### ISSUE THREAD

**Issue by lodebogaert** [Cereal2nd/velbus-aio#100]
Hi, after updating to 2024.5.3 my kwh-counter returned ‘unavailable’, for both the kw-sensor as the kWh-counter.
I tried deleting the cache en doing a new fresh scan, but after a reload the status still returned ‘unavailable’. I noticed the module found 2 new sensors: a binary sensor kwh and a virtual button.

Restoring a backup to 2024.5.2 didn’t solve the issue.
Restoring to 2024.1.6 fixed it for me.

Grt

**Comment by Cereal2nd** [comment]
should be fixed in the 2024.6 release

**Comment by lodebogaert** [comment]
Hi, I updated today from 2024.1.6 to 2024.6.3. At the initial load of HA everything worked fine. After another restart, I encountered the same issue. Is there some extra info/logs I can provide you to see what's going wrong?
