### ISSUE TITLE
VMB7IN module sensors “unavailable”

### ISSUE THREAD

**Issue by lodebogaert** [Cereal2nd/velbus-aio#109]
Hi, I updated today from 2024.1.6 to 2024.6.3. At the initial load of HA everything worked fine. After another restart, I encountered the same issue. Is there some extra info/logs I can provide you to see what's going wrong?

_Originally posted by @lodebogaert in https://github.com/Cereal2nd/velbus-aio/issues/100#issuecomment-2171368832_

**Comment by Cereal2nd** [comment]
this should have been fixed in 2024.7
