### ISSUE TITLE
Optimize the cache system

### ISSUE THREAD

**Issue by Cereal2nd** [Cereal2nd/velbus-aio#119]
i think we can optimize something here, previously we used python pickle to generate the cache for a module, this would save all info for a module/channel.
This system changed recently to a json cache file. Since then we only store the minimal needed info in the cache, so now we could optimize this to only write the files during a scan.

#113

**Comment by KevChief** [comment]
That definitely sounds interesting; right now I indeed don't see the benefit or the purpose of a constant rewrite and edit of the cache when there is no difference in set-up of the Velbus system. Once the scan is fully done, the cache is complete until a next scan happens which could mean changes of the set-up happened (new modules, renames, other configuration) which triggers new cache JSON files.

So this sounds logical to me as well that this could be a one time (during scan) write of cache as an optimisation , unless we are missing something here right now
