### ISSUE TITLE
Gap with the sensor's name of VMBGPO and VMBELO 

### ISSUE THREAD

**Issue by Benoit-P** [Cereal2nd/velbus-aio#24]
I run version 2021.11.5 of Home Assistant and with the VMBELO there is a gap in the sensor list. Where Velbuslink indicates heater, pump and Alarm1 pressed, HA indicates boost and cooler active. The same occurs with the VMBGPO modules.

**Comment by Cereal2nd** [comment]
so what exactly is wrong?

we use this data file
https://github.com/StefCoene/moduleprotocol/blob/master/protocol.json#L12102

**Comment by Benoit-P** [comment]
From CH1 to CH32 : no problem, temperature sensor is also good
What I see is a gap of 2. Alarm4 in velbuslink acivates Alarm2 in HA. See in the table below
VMBGPO
Home Assistant     Velbuslink
-----------------      -----------
Alarm2 (CH40)        Alarm4 (CH42)
Pump   (CH37         Alarm1 (CH39)
Cooler  (CH38)        Alarm2 (CH40)
Alarm1 (CH39)        Alarm3 (CH41)
Heater (CH35)         Pump (CH37)
N/A                         Heater (CH35)
N/A                         Boost (CH36)

Now, The VMBELO has sometimes a gap and what I noticed is that the HA sensors not always react or not immediately. For other modules like VMB4DC, sometimes I don't see any light active in HA when really it is and restarting HA server doesn't solve this problem

**Comment by Benoit-P** [comment]
still have the same problem with HA cersion 2022.2.6 and OS 7.
![vmbgpo gap ch32 to ch42](https://user-images.githubusercontent.com/6180447/155169264-7180b9fa-ef29-465b-93dd-b16232963d31.JPG)
![vmbgpo gap ch32 to ch42 velbulink](https://user-images.githubusercontent.com/6180447/155169372-0e2794f5-150f-4a1d-ab9d-83d1ac9a3a30.JPG)

4

**Comment by Cereal2nd** [comment]
Indeed no action was taken yet

I lack the time to investigate this

**Comment by Cereal2nd** [comment]
looking at this this seems to be a problem with the sub-addresses of these modules

can you get me a diagnostics info from this module in hass?
![afbeelding](https://user-images.githubusercontent.com/3715825/189822200-6b9ce760-e10c-4425-ab7d-f9f07313a11b.png)

**Comment by Benoit-P** [comment]
Hello Maikel,

My house has been sold and I’m building a new one. Now living without domotics !

Benoît

 

De : Maikel Punie ***@***.***> 
Envoyé : mardi 13 septembre 2022 08:05
À : Cereal2nd/velbus-aio ***@***.***>
Cc : Benoit-P ***@***.***>; Author ***@***.***>
Objet : Re: [Cereal2nd/velbus-aio] Gap with the sensor's name of VMBGPO and VMBELO (Issue #24)

 

looking at this this seems to be a problem with the sub-addresses of these modules

can you get me a diagnostics info from this module in hass?
 <https://user-images.githubusercontent.com/3715825/189822200-6b9ce760-e10c-4425-ab7d-f9f07313a11b.png>

**Comment by Benoit-P** [comment]
I don't think it's a problem with the sub-addresses !
The gap comes below the "Heater" sensor which is not a push button and this can cause the gap

**Comment by DannyDeGaspari** [comment]
Issue most probably solved by [https://github.com/Cereal2nd/velbus-aio/pull/66](url)
