### ISSUE TITLE
Replace python-velbus with velbus-aio

### ISSUE THREAD

**Issue by deweirdt** [Cereal2nd/velbus-aio#25]
Hi,

Not sure if it's relavant for this group, but do you have some documentation how to replace the python-velbus in HA with the velbus-aio?
I'm not sure how the python-velbus or velbus-aio is bound to the HA (core-2021.9.7)

**Comment by Cereal2nd** [comment]
this is implemented from the 2021.10 release

2021.10 and later: velbusaio
2021.9 and earlier: python-velbus

**Comment by deweirdt** [comment]
but I can't overrule this without a update of HA?

**Comment by Cereal2nd** [comment]
No this was a rewrite of the velbus component in home assistant.
So not possible
