### ISSUE TITLE
Python 3.10 incompatible

### ISSUE THREAD

**Issue by frenck** [Cereal2nd/velbus-aio#29]
Hi! 👋 

I've been working on upgrading Home Assistant to Python 3.10, and noticed this package isn't compatible with Python 3.10.

Python upgrade PR: <https://github.com/home-assistant/core/pull/59729>

Error from tests:

```
  File "/__w/core/core/venv/lib/python3.10/site-packages/velbusaio/protocol.py", line 51, in __init__
  self._send_queue = asyncio.Queue(loop=self._loop)
  TypeError: As of 3.10, the *loop* parameter was removed from Queue() since it is no longer necessary
```

A quick sneak peek/search revealed more cases of passing the loop argument:

<https://github.com/Cereal2nd/velbus-aio/search?q=loop>

Could this be fixed? 🙏  ❤️ 

Thanks!

../Frenck

**Comment by Cereal2nd** [comment]
Started working on this
https://github.com/Cereal2nd/velbus-aio/compare/py310
