### ISSUE TITLE
Cover set position available?

### ISSUE THREAD

**Issue by FinalFrag** [Cereal2nd/velbus-aio#31]
Is there a reason why support_position returns False, while you do have an implementation for the set_position method? I was hoping to get set position working from home assistant.

https://github.com/Cereal2nd/velbus-aio/blob/7fb693528d429661b804f8ed463da8f66ddfcef1/velbusaio/channels.py#L198

https://github.com/Cereal2nd/velbus-aio/blob/7fb693528d429661b804f8ed463da8f66ddfcef1/velbusaio/channels.py#L219

**Comment by Cereal2nd** [comment]
it depends on the modules, some modules do support it, others don't
