### ISSUE TITLE
VMBPIRO not sending motion updates

### ISSUE THREAD

**Issue by darkpainy** [Cereal2nd/velbus-aio#40]
Hi,

I noticed that my VMBPIRO (outdoor sensor) is not giving any motion updates to HA, the sensor is not dead as it work in the velbus automations and HA is picking up the Temperature and light sensor updates, but not the Motion.

Kind regards,
Jeroen

**Comment by Cereal2nd** [comment]
Confirmed, we only read in the light value from this message ...
`
        elif isinstance(message, ModuleStatusPirMessage):
            await self._channels[CHANNEL_LIGHT_VALUE].update(
                {"cur": message.light_value}
            )
`
