### ISSUE TITLE
Temperature flip-flops between low/high precision data 

### ISSUE THREAD

**Issue by niobos** [Cereal2nd/velbus-aio#50]
Hi,

I discovered some behavior of velbus-aio that I would like to change. I'm willing to fix this in a PR, but since the current behavior is technically correct, this isn't a simple bug and needs discussing first. Hence this issue.

A temperature sensor (VMB1TS, VMBGP*) can report its current temperature in two forms:

* A [Temperature Sensor Status](https://github.com/Cereal2nd/velbus-aio/blob/23c9d1e4030a491bea4bcbea22709c29c41fff74/velbusaio/messages/temp_sensor_status.py#L16) message, containing the temperature with 1/2°C precision.
* A [Temperature Sensor](https://github.com/Cereal2nd/velbus-aio/blob/23c9d1e4030a491bea4bcbea22709c29c41fff74/velbusaio/messages/sensor_temperature.py#L14) message, containing the temperature with 1/16ºC precision.

Currently, [the last received message is used to update the state](https://github.com/Cereal2nd/velbus-aio/blob/master/velbusaio/module.py#L283-L303) of the temperature channel.

When graphing the temperature data, this causes "glitches" in the high-precision graph when a low-precision message is received: Note the sudden drop to 19.0°C around 9:30 
<img width="780" alt="Screenshot 2022-10-24 at 10 23 11" src="https://user-images.githubusercontent.com/1756905/197481334-4beb993c-4c57-4fbd-8322-d1217de2cbed.png">

I'm open to discuss this: Do you consider this current behavior as "as designed", or are you open for "improvements"?

One way to enhance this would be to only use the low-res message when it's more than 1/2°C away from the last high-res message.

**Comment by Cereal2nd** [comment]
maybe its best to round this value always to the 1/2°C, this will give the most consistent data

**Comment by niobos** [comment]
> maybe its best to round this value always to the 1/2°C, this will give the most consistent data

That would be consistent, but you'd loose the high precision output.

> or maybe ignore the temp status message if there is already data in the sensor

This is kind of what I proposed: If the current data in memory is reasonable with the received low-res data, ignore the update; but if the low-res data indicates a (big enough) change in temperature, do update nevertheless.

**Comment by Cereal2nd** [comment]
Go for it, the second part.
It's a relative simple fix

**Comment by Cereal2nd** [comment]
@niobos are you already working on a fix for this? if not i'll start working on one

**Comment by niobos** [comment]
It looks like the temperature in the Temperature Sensor Status message is the truncated version of the temperature in the Temperature Sensor message. I.e. rounded down (at least for positive temperatures):
<img width="776" alt="Screenshot 2022-10-30 at 14 11 21" src="https://user-images.githubusercontent.com/1756905/198880258-4041d552-354e-4d86-a184-8b5cd1a67d51.png">

However, I can't find an algorithm that does "the right thing" in all circumstances. I'll be thinking about this further...

**Comment by niobos** [comment]
To clarify some examples. The "Message temp" column indicates the value is the message; a 1-decimal-digit message indicates a Temperature Sensor Status message, a 4-decimal-digit message indicates a Temperature Status message. **Bold** values indicate unwanted behavior.

 1. State 1 is the current de-facto behavior: it keeps the value of the most recent message
 2. State 2 was the idea pitched above: Only update if the message is contradicting the stored value. This breaks when temperature is going down


| Actual temp | Message temp | State 1     | State 2     |
| ----------- | ------------ | ------------| ----------- |
| 20.4375     | 20.0         | 20.0        | 20.0        |
| 20.4375     | 20.4375      | **20.4375** | 20.475      |
| 20.4375     | 20.0         | **20.0**    | 20.475      |
| 20.4375     | 20.4375      | **20.4375** | 20.475      |
| 20.5000     | 20.5         | 20.5        | 20.5        |
| 20.5625     | 20.5625      | 20.5625     | 20.5625     |
| 20.6250     | 20.5         | 20.5        | 20.5625     |
| 20.5625     | 20.5625      | 20.5625     | 20.5625     |
| 20.5000     | 20.5         | 20.5        | 20.5625     |
| 20.5000     | 20.5000      | 20.5        | **20.5**    |
| 20.4375     | 20.0         | 20.0        | **20.0**    |
| 20.4375     | 20.4375      | 20.4375     | **20.4375** |

**Comment by Cereal2nd** [comment]
the other solution is to always rounf the value received to 1/2C, then it will always be correct

**Comment by ggaljoen** [comment]
Maybe a late (stupid?) suggestion; to choose to have the choice to use either one or the other?
I prefer the more specified for more details.

**Comment by Cereal2nd** [comment]
> Maybe a late (stupid?) suggestion; to have the choice to use either one or the other? I prefer the more specified for more details.

this would involve a lot of work, but its possible

1- implement the options flow in the integration
2- pass the options from the options flow towards velbusaio
3- if this param is set either round the 1/16C towards 1/2C or ignore the 1/2C messages

**Comment by niobos** [comment]
> the other solution is to always round the value received to 1/2C, then it will always be correct. But this will make the sensor less accurate, but i think its ok

That would be correct, but unacceptable for my use-case.

I've implemented something I find acceptable in #52. Feedback welcome.
