### ISSUE TITLE
Support VMB4AN velbus

### ISSUE THREAD

**Issue by DePutjes** [Cereal2nd/velbus-aio#76]
Analog values ​​from VMB4AN (velbus) are not read correctly in Home assistant. They always remain at a value of zero.
[vmb4an.pdf](https://github.com/Cereal2nd/velbus-aio/files/10323230/vmb4an.pdf)

**Comment by jeroends** [comment]
Hello, same problem here, module gives me a lot of errors:
![image](https://user-images.githubusercontent.com/2332873/212552937-acd28254-b886-44b9-893a-95d26bcd4de6.png)

**Comment by Cereal2nd** [comment]
I do not own this module and certainly did not test it.

If there is someone who has this module and can get me the output of a examples/loadmodules.py I can have a look.

**Comment by wardhou** [comment]
Hi

We have a number of vmb4an devices in our installations. I would love to read theme. Is there anything I can do to provide you with information?

**Comment by MDAR** [comment]
@Cereal2nd 
As always, you are welcome to remotely connect to one of my demo units with the module you want to explore / test.

With the VMB4AN, I can hang a number of different sensors on it.

Please just ask.

**Comment by Cereal2nd** [comment]
2023.10.2 will fix this

and hopefully this will make it to the .11 release in hass
