### ISSUE TITLE
vmb1dm not working 

### ISSUE THREAD

**Issue by eamonnogorman** [Cereal2nd/velbus-aio#83]
Hi,

Would it be possible to take a look at this, or can anyone advise  if they have one working ?

Mine is detected by I can't do anything with it, buttons don't work and it does not display actual status

Regards
Eamon

**Comment by Cereal2nd** [comment]
If you can provide me with a test system I'll certainly implement this.

I do not own that module so it's difficult to implement.

**Comment by eamonnogorman** [comment]
I only have the one unit which is in use. Is there anything I can provide or capture for data that would help ?

**Comment by Cereal2nd** [comment]
Would it be an option that I connect remotely to your system to debug this?

If you can pass me an IP + port I can debug this and probably fix this.

**Comment by eamonnogorman** [comment]
Hi,

Sorry only saw the reply just now. Thanks for that, would a TeamViewer
access work ? Really appreciate it

**Comment by Cereal2nd** [comment]
teamviewer could work, but a simple ip:port would be a lot faster

**Comment by eamonnogorman** [comment]
Ok, so I need to setup port forwarding on my router, I don't have fixed IP
address?

**Comment by Cereal2nd** [comment]
yeah if you can setup a port forward for a couple of days this would help a lot

**Comment by eamonnogorman** [comment]
Hi Maikel,

If I don't have a fixed public IP, how do you access it, as the public IP
will change ?

I could either setup an account on my home assistant cloud for you ?

**Comment by Cereal2nd** [comment]
Normally your fixed IP stays for a couple of days.
i only need access for one, maybe 2 days. So do not worry about it :)

Maikel

**Comment by Cereal2nd** [comment]
can you check this again?

**Comment by Cereal2nd** [comment]
should be fixed in 2024.6
