### ISSUE TITLE
VMBGP4PIR-20 support

### ISSUE THREAD

**Issue by dverhelst** [Cereal2nd/velbus-aio#91]
Hi, 
The updated VMBGP4PIR-20 new series does not seem to work.

`DEBUG:velbus-protocol:RX: RawMessage(priority=fb, address=a9, rtr=False, command=255, data=b'ff 5f 8a 7b 04 23 48 20')
DEBUG:velbus-packet:Received {"name": "ModuleTypeMessage", "priority": 251, "address": 169, "rtr": false, "data": "", "module_type": 95, "led_on": [], "led_slow_blinking": [], "led_fast_blinking": [], "serial": 35451, "memory_map_version": 4, "build_year": 72, "build_week": 32}
WARNING:velbus-packet:Module not recognized: 95
DEBUG:velbus-protocol:TX: RawMessage(priority=fb, address=ab, rtr=True, command=None, data=b'')
DEBUG:velbus-protocol:RX: RawMessage(priority=fb, address=a9, rtr=False, command=176, data=b'b0 5f 8a 7b b9 ff ff ff')
DEBUG:velbus-packet:Received {"name": "ModuleSubTypeMessage", "priority": 251, "address": 169, "rtr": false, "data": "", "module_type": 95, "sub_address_1": 185, "sub_address_2": 255, "sub_address_3": 255, "sub_address_4": 255, "serial": 35451, "sub_address_offset": 0}`

Upstream seems to have added the [moduleprototol - Add new edgelit and glasspanel series protocol](https://github.com/velbus/moduleprotocol/commit/939b18609bf869f332a777e42e180d14de726297)

**Comment by Cereal2nd** [comment]
should be solved with https://github.com/Cereal2nd/velbus-aio/commit/5512c8a14c5d985eb1cc3ec79da74314a3aa3f05
